server:
  port: 8762

spring:
  application:
    name: order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

user:
  ribbon:
  #负载均衡采用随机策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

