
server:
  port: 8763

#服务名称
spring:
  application:
    name: user
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=UTC

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    register-with-eureka: true
    #是否需要从eureka上获取注册信息
    fetch-registry: true
feign:
  hystrix:
    enabled: true   #打开Feign自带的断路器